# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8aa7c77762c26e5929f941a6c10974e1f1029a2285c31f0c77ac679b72f35ece79339c580f3d98962046698b720805286be39e6bf0d5ac5d79604bcf5ed9ef9

test:
  secret_key_base: 0b4d1bf91ff5cbcdbbd5dc095ade77459ed39fd32028ba7fcb3cfb4b154fbd7c292293223f75a9303bf1b6a91c2593e7f0c0e369878147ea65b976d6a58af388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
